### ISSUE TITLE
ng-toggle-btn color and attributes are not showing off (closed) --- ng-toggle-btn value

### ISSUE THREAD

**Issue by nurisanendita** [shijukbabu/ng-toggle-btn#2]
I'm sorry for apply the issue. Now, my toggle switch btn is working. The problem is in module injections apiService, that make the ng-toggle.btn module is not working.

I want to ask about the toggle siwtch button value asignned. What class did store the value when the toggle switch button is on? I need to put a value when the toggle switch button is on. 
Thank you very much.

**Comment by shijukbabu** [comment]
Glad, the directive is helpful
